import os
import shutil
import stat
import subprocess
from typing import Optional
from web2gtk.manifest import AppManifest
from web2gtk.icons import install_local_icon, fetch_web_icon, SIZES, ICON_BASE

BIN_DIR = os.path.expanduser("~/.local/bin")
DESKTOP_DIR = os.path.expanduser("~/.local/share/applications")


def refresh_system_caches():
    """Trigger update of desktop database and GTK icon caches."""
    if shutil.which("update-desktop-database"):
        subprocess.run(
            ["update-desktop-database", DESKTOP_DIR],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL
        )
    if shutil.which("gtk-update-icon-cache"):
        subprocess.run(
            ["gtk-update-icon-cache", "-f", "-t", ICON_BASE],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL
        )


def install_app(manifest: AppManifest, icon_path_or_url: Optional[str] = None) -> bool:
    """Generate and install an app: icon, desktop entry, launcher, and manifest."""
    os.makedirs(BIN_DIR, exist_ok=True)
    os.makedirs(DESKTOP_DIR, exist_ok=True)

    # 1. Process Icon
    if icon_path_or_url and os.path.exists(icon_path_or_url):
        install_local_icon(icon_path_or_url, manifest.icon)
    else:
        fetch_web_icon(manifest.url, manifest.icon, manifest.name)

    # 2. Save Manifest
    manifest.save()

    # 3. Create Launcher Script in ~/.local/bin/<slug>
    launcher_path = os.path.join(BIN_DIR, manifest.slug)
    launcher_content = f"""#!/usr/bin/env bash
# Auto-generated by web2gtk for {manifest.name}
exec web2gtk-runner "{manifest.slug}" "$@"
"""
    with open(launcher_path, "w", encoding="utf-8") as f:
        f.write(launcher_content)
    
    # Make launcher executable
    current_stat = os.stat(launcher_path)
    os.chmod(launcher_path, current_stat.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    # 4. Create .desktop file
    desktop_path = os.path.join(DESKTOP_DIR, f"{manifest.slug}.desktop")
    desktop_content = f"""[Desktop Entry]
Version=1.0
Type=Application
Name={manifest.name}
Comment=Native web desktop app for {manifest.name}
Exec={launcher_path} %U
Icon={manifest.icon}
Terminal=false
Categories=Network;WebBrowser;Utility;
StartupWMClass={manifest.app_id}
MimeType=x-scheme-handler/{manifest.slug};
Keywords=web;{manifest.name.lower()};
"""
    with open(desktop_path, "w", encoding="utf-8") as f:
        f.write(desktop_content)

    # 5. Refresh system caches
    refresh_system_caches()
    return True


def uninstall_app(slug: str, purge_data: bool = False) -> bool:
    """Remove desktop entry, launcher, icons, manifest, and optionally data."""
    try:
        manifest = AppManifest.load(slug)
    except FileNotFoundError:
        manifest = None

    actual_slug = manifest.slug if manifest else slug

    # Remove desktop entry
    desktop_file = os.path.join(DESKTOP_DIR, f"{actual_slug}.desktop")
    if os.path.exists(desktop_file):
        os.remove(desktop_file)

    # Remove launcher
    launcher = os.path.join(BIN_DIR, actual_slug)
    if os.path.exists(launcher):
        os.remove(launcher)

    # Remove icons
    icon_name = manifest.icon if manifest else actual_slug
    for size in SIZES:
        icon_file = os.path.join(ICON_BASE, f"{size}x{size}", "apps", f"{icon_name}.png")
        if os.path.exists(icon_file):
            os.remove(icon_file)

    # Remove manifest
    if manifest:
        manifest.delete()

    # Optionally purge data directories
    if purge_data:
        for p in [
            os.path.expanduser(f"~/.local/share/{actual_slug}"),
            os.path.expanduser(f"~/.cache/{actual_slug}"),
            os.path.expanduser(f"~/.config/{actual_slug}"),
        ]:
            if os.path.exists(p):
                shutil.rmtree(p, ignore_errors=True)

    refresh_system_caches()
    return True
